name: Release

on:
  push:
    branches: [ master ]

jobs:
  job_1:
    name: publish to NPM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
    - run: yarn install
    - run: yarn npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}